# Generated by Django 4.2.15 on 2024-09-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_district_order_id_region_order_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="social",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "social",
                    models.CharField(
                        choices=[
                            ("telegram", "Telegram"),
                            ("instagram", "Instagram"),
                            ("facebook", "Facebook"),
                            ("youtube", "Youtube"),
                        ],
                        max_length=16,
                    ),
                ),
                ("link", models.URLField()),
            ],
        ),
        migrations.AlterModelOptions(
            name="district",
            options={"ordering": ["order_id", "id"]},
        ),
        migrations.AlterModelOptions(
            name="region",
            options={"ordering": ["order_id", "id"]},
        ),
    ]
