# Generated by Django 4.2.15 on 2024-09-01 14:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Director",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", ckeditor.fields.RichTextField()),
                ("phone_number", models.CharField(max_length=255)),
                ("picture", models.ImageField(upload_to="images")),
            ],
        ),
    ]
