# Generated by Django 4.2.15 on 2024-09-01 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("education", "0002_director_full_name_faculty"),
    ]

    operations = [
        migrations.CreateModel(
            name="Direction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "education_type",
                    models.CharField(
                        choices=[
                            ("daytime", "Kunduzgi"),
                            ("part_time", "Sirtqi"),
                            ("evening", "Kechgi"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="education.faculty",
                    ),
                ),
            ],
        ),
    ]
