# Generated by Django 4.2.16 on 2024-09-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("education", "0003_direction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="direction",
            name="language",
            field=models.CharField(
                choices=[
                    ("uz", "O'zbek tili"),
                    ("ru", "Rus tili"),
                    ("en", "Ingiliz tili"),
                ],
                max_length=20,
            ),
        ),
    ]
