# Generated by Django 4.2.16 on 2024-09-06 12:40

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("education", "0004_alter_direction_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="direction",
            name="body",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="direction",
            name="faculty",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="directions",
                to="education.faculty",
            ),
        ),
    ]
